name: CI

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: '0 7 * * *'

jobs:
  build:
    runs-on: self-hosted
    container:
        image: ghcr.io/gmto/gmt-base-os:alma9
    steps:
        - name: Clone dev_fwk
          uses: actions/checkout@v4
          with:
            repository: GMTO/ocs_dev_fwk
            ref: master
            token: ${{secrets.GH_PAT}}
            path: ocs_dev_fwk

        - name: Install dev_fwk
          uses: ./ocs_dev_fwk/etc/ci/actions/setup-gmt
          with:
            token: ${{secrets.GH_PAT}}

        - name: SDK version
          id: sdk_version
          run: |
            sdk=gmt-sdk-$(date -u +"%Y%m%d-%H%M%S").tar.gz
            echo sdk="$sdk" >> $GITHUB_OUTPUT

        - name: Build SDK components
          id: build_sdk
          run: |
            echo "::group::setup gds"
            source /root/.bashrc
            echo "::endgroup::"

            echo "::group::gds clone"
            gds clone --bundle ocs_sdk_bundle
            echo "::endgroup::"

            echo "::group::gds build"
            gds build --bundle ocs_sdk_bundle
            echo "::endgroup::"

            echo "::group::gds install"
            gds install --bundle ocs_sdk_bundle
            echo "::endgroup::"

            echo "::group::grs compile"
            grs compile core_fwk
            grs compile ctrl_fwk
            grs compile dp_fwk
            grs compile io_fwk
            grs compile pers_fwk
            grs compile ui_fwk
            grs compile log_sys
            grs compile alarm_sys
            grs compile tele_sys
            grs compile conf_sys
            grs compile sup_sys
            grs compile data_sys
            grs compile app_sys
            grs compile seq_sys
            echo "::endgroup::"

            echo "::group::gds test"
            # gds test --bundle ocs_sdk_bundle
            echo "::endgroup::"

            echo "::group::packaging"
            tar zcvf /tmp/${{ steps.sdk_version.outputs.sdk }} --exclude test --exclude ./modules --exclude ./node_modules --exclude ./python_modules --exclude ./package-lock.json -C /opt/gmt .
            echo "::endgroup::"
        - name: Upload SDK artifact
          uses: actions/upload-artifact@v4
          with:
              name: ${{ steps.sdk_version.outputs.sdk }}
              path: /tmp/${{ steps.sdk_version.outputs.sdk }}
              retention-days: 30
