name: CI

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  build:
    runs-on: self-hosted
    container:
        image: ghcr.io/gmto/gmt-base-os:alma9
    steps:
        - name: Clone dev_fwk
          uses: actions/checkout@v4
          with:
            repository: GMTO/ocs_dev_fwk
            ref: master
            token: ${{secrets.GH_PAT}}
            path: ocs_dev_fwk

        - name: Install dev_fwk
          uses: ./ocs_dev_fwk/etc/ci/actions/setup-gmt
          with:
            token: ${{secrets.GH_PAT}}

        - name: Build SDK components
          run: |
            source /root/.bashrc
            gds clone --bundle ocs_sdk_bundle
            gds build --bundle ocs_sdk_bundle
            # gds test  --bundle ocs_sdk_bundle
            tar zcvf ${{ github.workspace }}/gmt-sdk.tar.gz --exclude test --exclude modules --exclude node_modules --exclude python_modules -C /opt/gmt .
        - name: Upload SDK artifact
          uses: actions/upload-artifact@v2
          with:
              name: gmt-sdk.tar.gz
              path: ${{ github.workspace }}/gmt-sdk.tar.gz
              retention-days: 30
