on: [release]

jobs:
  gmt_checks:
    runs-on: ubuntu-latest
    name: GMT SDK build
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy CI Files
        run: cp -fr release/* .
      - name: Get release name
        id: release_name
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\/v/, '');
      - name: 'GMT SDK distribution'
        id: build_release
        uses: ./
        with:
          args: /module/create_build.sh ${{ steps.release_name.outputs.result }} # version (for the final release)
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: gmt-sdk-${{ env.version }}.tar.gz
          path: ${{ github.workspace }}/gmt-sdk-${{ steps.release_name.outputs.result }}.tar.gz
          retention-days: 180
      - name: 'GMT SDK test'
        id: test_release
        uses: ./
        with:
          args: /module/test_build.sh ${{ steps.release_name.outputs.result }} # version
