on: [release]

jobs:
  gmt_checks:
    runs-on: ubuntu-latest
    name: GMT SDK build
    env:
      PAT: ${{ secrets.PAT }}
      # Add pull request numbers separated by commas (,) below
      ocs_core_fwk_pull_requests: ""
      ocs_dev_fwk_pull_requests: ""
      ocs_sys_pull_requests: ""
      ocs_ctrl_fwk_pull_requests: ""
      ocs_dp_fwk_pull_requests: ""
      ocs_io_fwk_pull_requests: "140"
      ocs_pers_fwk_pull_requests: ""
      ocs_test_fwk_pull_requests: ""
      ocs_ui_fwk_pull_requests: ""
      # services
      ocs_log_sys_pull_requests: ""
      ocs_alarm_sys_pull_requests: ""
      ocs_tele_sys_pull_requests: ""
      ocs_conf_sys_pull_requests: ""
      ocs_sup_sys_pull_requests: ""
      ocs_da_sys_pull_requests: ""
      ocs_app_sys_pull_requests: ""
      ocs_seq_sys_pull_requests: ""
      # ext libraries
      ocs_nanomsg_ext_pull_requests: ""
      ocs_msgpack_ext_pull_requests: ""
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy CI Files
        run: cp -fr release/* .
      - name: Get release name
        id: release_name
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\/v/, '');
      - name: 'GMT SDK distribution'
        id: build_release
        uses: ./
        with:
          args: /module/create_build.sh ${{ steps.release_name.outputs.result }} # version (for the final release)
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: gmt-sdk-${{ env.version }}.tar.gz
          path: ${{ github.workspace }}/gmt-sdk-${{ steps.release_name.outputs.result }}.tar.gz
          retention-days: 180
      - name: 'GMT SDK test'
        id: test_release
        uses: ./
        with:
          args: /module/test_build.sh ${{ steps.release_name.outputs.result }} # version
