on: [push, pull_request]

jobs:
  gmt_checks:
    runs-on: ubuntu-latest
    name: GMT SDK build
    env:
      PAT: ${{ secrets.PAT }}
      version: "1.14.0"
      # Add pull request numbers separated by commas (,) below
      ocs_core_fwk_pull_requests: "291,292,297,298,299,300"
      ocs_dev_fwk_pull_requests: "133,134,135"
      ocs_sys_pull_requests: ""
      ocs_icds_pull_requests: ""
      ocs_ctrl_fwk_pull_requests: ""
      ocs_dp_fwk_pull_requests: ""
      ocs_io_fwk_pull_requests: "150,151"
      ocs_pers_fwk_pull_requests: "25"
      ocs_test_fwk_pull_requests: ""
      ocs_ui_fwk_pull_requests: ""
      # services
      ocs_log_sys_pull_requests: "39"
      ocs_alarm_sys_pull_requests: "49"
      ocs_tele_sys_pull_requests: "36"
      ocs_conf_sys_pull_requests: "40"
      ocs_sup_sys_pull_requests: "54"
      ocs_data_sys_pull_requests: "30"
      ocs_app_sys_pull_requests: "17"
      ocs_seq_sys_pull_requests: "42"
      # ext libraries
      ocs_boost_ext_pull_requests: ""
      ocs_eigen_ext_pull_requests: ""
      ocs_nanomsg_ext_pull_requests: ""
      ocs_msgpack_ext_pull_requests: ""
      ocs_slalib_ext_pull_requests: ""
      ocs_etherlabmaster_ext_pull_requests: ""
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy CI Files
        run: cp -fr release/* .
      - name: Get release name
        id: release_name
        run: echo "name=release_id::$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: 'GMT SDK distribution'
        id: build_release
        uses: ./
        with:
          args: /module/create_build.sh ${{ env.version }} ${{ steps.release_name.outputs.release_id }} # version date-commit
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: gmt-sdk-${{ env.version }}.${{ steps.release_name.outputs.release_id }}.tar.gz
          path: ${{ github.workspace }}/gmt-sdk-${{ env.version }}.${{ steps.release_name.outputs.release_id }}.tar.gz
          retention-days: 30
      - name: 'GMT SDK test'
        id: test_release
        uses: ./
        with:
          args: /module/test_build.sh ${{ env.version }} ${{ steps.release_name.outputs.release_id }} # version date-commit

